baseURL = "https://marzenakrp.github.io/"
languageCode = 'en-us'
title = 'Marzena Karpinska'
theme = "m10c"

[params]
  author = "Marzena Karpinska"
  description = "Senior Researcher at Microsoft"
  avatar = "/images/bio-photo.jpg"
  menu_item_separator = " // "

  # Define social links
  [[params.social]]
    name = "Twitter"
    icon = "twitter"
    url = "https://twitter.com/mar_kar_"
  [[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/marzenakrp"
  [[params.social]]
    name = "Google Scholar"
    icon = "book-open"
    url = "https://scholar.google.com/citations?user=-sWY5igAAAAJ&hl"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/"


[[menu.main]]
  identifier = "publications"
  name = "Publications"
  url = "/publications/"

[[menu.main]]
  identifier = "cv"
  name = "CV"
  url = "/marzena_karpinska.pdf"

  [[menu.main]]
  identifier = "Projects"
  name = "Projects"
  url = "/projects/"